### ISSUE TITLE
Official Sylius plugin

### ISSUE THREAD

**Issue by Zales0123** [gewebe/SyliusProductDepositPlugin#1]
Hello!

I'm Mateusz, I work in Sylius company and one of my roles is Plugin Curator - I'm responsible for checking out Sylius Plugins that appear in our ecosystem. We would really love to display this one on our officially accepted plugins list (https://sylius.com/plugins/), as I strongly believe it could be useful for other people in the community :)

The only problem is, we have some strict requirements for the plugin that is meant to be displayed on our website. One of the most important are the properly developed tests. Sadly, your plugin has neither unit (PHPSpec/PHPUnit) nor acceptance (Behat) tests. Do you think you would be able to provide them? It would be great if we could extend our accepted plugins set with SyliusDepositPlugin :)

If you have any question, please, feel free to ask me.
Nevertheless, thank you for choosing Sylius and for your great job!

**Comment by gewebe** [comment]
Hi Mateusz

Sorry for the long response time.
Now i added some behat and phpspec tests and created a preview release. I would be glad about any feedback to tell me if I'm on the right way for an official plugin.

**Comment by Zales0123** [comment]
This time, apologize from my side for the long response time 🖖 :) I promise I'll take a look at your changes ASAP and let you know. Thanks for your effort!

**Comment by gewebe** [comment]
No worries, thanks for taking the time!
Since the plugin is official on the sylius website now, i closed this issue. But i am happy for any recommendation to make it better.
