### ISSUE TITLE
Error installing using composer

### ISSUE THREAD

**Issue by asterix11** [gewebe/SyliusProductDepositPlugin#3]
I'm facing the following issue:
![image](https://user-images.githubusercontent.com/11007901/152662906-b7a71ea9-8407-41ce-bf84-6ce9e8862e24.png)

Which further information do you need in order to identify the issue?
The error message appeared right after running `composer require gewebe/sylius-product-deposit-plugin`

Sylius version: 1.10

**Comment by gewebe** [comment]
The package has no recipe so far, you have to follow the [install instructions](https://github.com/gewebe/SyliusProductDepositPlugin#installation) 
After enabling the plugin at your bundels.php the error will disappear.

**Comment by asterix11** [comment]
Thanks for your prompt answer, unfortunately the addition of the following line, as mentioned in the documentation, to the bundles array didn't lead to success:
```php
Gewebe\SyliusProductDepositPlugin\GewebeSyliusProductDepositPlugin::class => ['all' => true],
```

**Comment by asterix11** [comment]
@gewebe May you be so kind so clarify this? I'm new to PHP development with Symfony and even if it is my fault, which would be very ok, it's not clear to me, where i should search.

**Comment by gewebe** [comment]
If all steps of the installation are done, the plugin should work as described. i can check it again in the next weeks.
